# Generated by Django 4.1.3 on 2022-12-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('affiliated_agency', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('project_start_time', models.DateField()),
                ('project_completion_time', models.DateField()),
                ('total_budget', models.IntegerField()),
                ('completion_percentage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='uploaddetails',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=200)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.details')),
            ],
        ),
    ]
