# Generated by Django 4.1.3 on 2022-12-18 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_details_alter_uploaddetails_file_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
