# Generated by Django 4.1.3 on 2022-12-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0003_details_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='completion_percentage',
            field=models.FloatField(),
        ),
    ]
