# Generated by Django 4.1.3 on 2022-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0006_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='issue_count',
            field=models.IntegerField(default=0),
        ),
    ]
